- sumpy/expansion/__init__.py
@isuruf, could you take a look and help get this right?
> Fix LinearPDEBasedExpansionTermsWrangler.get_projection_matrix docstring

- requirements.txt
- sumpy/e2e.py
- sumpy/e2p.py
- sumpy/expansion/local.py
- sumpy/expansion/multipole.py
- sumpy/fmm.py
- sumpy/p2e.py
- sumpy/p2p.py
- sumpy/qbx.py
- sumpy/tools.py
- sumpy/toys.py
- test/test_codegen.py
- test/test_fmm.py
- test/test_kernels.py
Needs https://github.com/inducer/boxtree/pull/20
Testing pytential in inducer/pytential#33
> Allow multiple kernels in p2e

- .github/workflows/ci.yml
- .gitlab-ci.yml
- .test-conda-env-py3.yml
- examples/curve-pot.py
- examples/expansion-toys.py
- examples/sym-exp-complexity.py
https://gitlab.tiker.net/inducer/sumpy/-/merge_requests/145
> Ci examples

- sumpy/expansion/multipole.py
- sumpy/kernel.py
- sumpy/qbx.py
- test/test_fmm.py
> Add AxisSourceDerivative

- setup.py
- sumpy/e2p.py
- sumpy/p2e.py
- sumpy/p2p.py
- sumpy/qbx.py
- sumpy/tools.py
- Needed for https://github.com/inducer/loopy/pull/242
> Make explicit the redundant execution of kernel scaling assignments

- sumpy/expansion/__init__.py
- sumpy/expansion/local.py
- sumpy/expansion/multipole.py
- sumpy/kernel.py
Should fix https://github.com/inducer/sumpy/issues/33 too
> Move derivative taker to Kernel

- sumpy/e2e.py
Helps to run the benchmarks easily in loopy
> Make get_translation_loopy_insns a memoize method

- sumpy/expansion/local.py
- sumpy/qbx.py
- test/test_qbx.py
Fixes https://github.com/inducer/pytential/issues/53.
cc @xywei
> Fix direct-evaluation QBX with target derivatives

- sumpy/expansion/local.py
- sumpy/expansion/multipole.py
Fixes https://gitlab.tiker.net/inducer/loopy/-/issues/224
cc @kaushikcfd
> Fix deprecated *Conforming expansions

- sumpy/codegen.py
See https://github.com/inducer/sumpy/pull/40#issuecomment-852635444 for context.
cc @isuruf @kaushikcfd
> Stop using combine_mappers for the moment

- .github/workflows/ci.yml
- sumpy/e2e.py
- sumpy/e2p.py
- sumpy/kernel.py
- sumpy/p2e.py
- sumpy/p2p.py
- sumpy/qbx.py
- sumpy/toys.py
- test/test_fmm.py
To reproduce the results of https://doi.org/10.1016/j.jcp.2007.06.029
> Add TargetPointMultiplier

- .github/workflows/ci.yml
- requirements.txt
- sumpy/codegen.py
- sumpy/kernel.py
> Adapt codegen to loopy kernel callables

- sumpy/kernel.py
Mostly copied form the [ElasticityKernel](https://github.com/inducer/sumpy/blob/a9a6806329cd2043a8d7aff9cd2f7a7131f153eb/sumpy/kernel.py#L747-L752), which already uses `get_all_variables`.
For some context, I was just setting `mu_sym = 1` in the kernel (for non-dimensional equations) and loopy wasn't happy that it got a number as a `ValueArg`.
> Fix get_args for Stresslet kernel

- sumpy/tools.py
Managed to see this on a profile, which was pretty cool!
> Do not use generator in add_mi

- .gitlab-ci.yml
- asv.conf.json
Investigating [this failure](https://gitlab.tiker.net/inducer/sumpy/-/jobs/353988) that came about after merging https://github.com/inducer/sumpy/pull/70.
cc @isuruf
Gitlab: https://gitlab.tiker.net/inducer/sumpy/-/merge_requests/151
> Putz around with benchmark Gitlab CI task to avoid failures

- sumpy/visualization.py
Actual reason for inducer/pyvisfile#27!
> Allow overwriting in FieldPlotter.write_vtk_file

- sumpy/cse.py
https://github.com/sympy/sympy/pull/22335
> Update deprecated call to sympy.compatibility.iterable

- .github/workflows/ci.yml
- .gitlab-ci.yml
> Various CI improvements

- sumpy/tools.py
- test/test_kernels.py
Fixes #107 
Regression from #26 
Also adds a test for 3D kernels in test_translations.
> Fix HelmholtzDerivativeTaker

- test/test_kernels.py
Checks that the error is of the same order as the truncation error.
> Add test for compressed Helmholtz error

- contrib/translations/PDE-reduction-symbolic.ipynb
- sumpy/expansion/level_to_order.py
- sumpy/expansion/local.py
- sumpy/expansion/multipole.py
- sumpy/tools.py
For context, just fixing these because `pytential` started showing loads of deprecation warnings :cry:
> Remove uses of pytools.factorial

- sumpy/e2e.py
- test/test_fmm.py
> Fix, test order varying with level

- .github/workflows/ci.yml
- sumpy/fmm.py
Needed for https://github.com/inducer/sumpy/pull/113 to get one of the tests to pass with FFT.
> Use a better rscale from Greengard 1988

- sumpy/kernel.py
Thoughts? Was looking at too many of these in inducer/pytential#152 and this looked prettier..
> Use unicode in DirectionalDerivative.__str__

- doc/conf.py
- doc/misc.rst
- sumpy/kernel.py
- sumpy/symbolic.py
Partially fixes https://github.com/inducer/pytential/issues/116
> Add SpatialConstant

- sumpy/p2p.py
> Fix code folding after f-string use in P2P

- sumpy/e2e.py
> Disable global barrier check in translation-classes-dep data generation

- .test-conda-env-py3.yml
- sumpy/distributed.py
- test/test_distributed.py
> Add distributed wrangler

- sumpy/expansion/diff_op.py
Latest version seems to have changed some things in an incompatible way.
> Fix for pyrsistent changes

- requirements.txt
- sumpy/p2p.py
> Use a vec array for local_isrc* for coalesced array access

- sumpy/tools.py
https://github.com/PyCQA/flake8-bugbear/releases/tag/23.2.13
> Silence new flake8-bugbear B028 error

- sumpy/expansion/m2l.py
gives a 40% performance boost in CUDA
> Optimize M2L a bit

- sumpy/expansion/__init__.py
- sumpy/expansion/local.py
- sumpy/kernel.py
> Fix type comparison

- doc/conf.py
- doc/misc.rst
- sumpy/array_context.py
- sumpy/tools.py
Moved these out of #118 to make that nasty diff smaller. This mostly adds docs (the commits should be fairly self-explanatory).
> Some small cleanups in sumpy.tools

- sumpy/visualization.py
https://github.com/pylint-dev/pylint/issues/9989
> Placate pylint about new bug

- examples/curve-pot.py
- examples/expansion-toys.py
- examples/sym-exp-complexity.py
- sumpy/array_context.py
- sumpy/codegen.py
- sumpy/kernel.py
- sumpy/symbolic.py
- test/test_fmm.py
.. it's just `SpatialConstant`.
The `PersistentHashWalkMapper` changes are probably worth taking a look at, since I'm not quite familiar with that.
> Remove some deprecations from dataclass Expressions

- sumpy/codegen.py
- sumpy/expansion/loopy.py
- sumpy/expansion/m2l.py
- sumpy/tools.py
- sumpy/visualization.py
- test/test_cse.py
Found most of these while looking through pytential warnings.
> Fix some loopy deprecations

- .basedpyright/baseline.json
- doc/conf.py
- sumpy/codegen.py
- sumpy/derivative_taker.py
- sumpy/e2e.py
- sumpy/expansion/diff_op.py
- sumpy/kernel.py
- sumpy/symbolic.py
- sumpy/tools.py
> Improve kernel type annotations
