inducer/sumpy

sumpy/p2p.py
Required by inducer/pytential#71. (turns out it was just a cache invalidation issue!)
=> Allow offsets in P2P kernel

sumpy/codegen.py, sumpy/expansion/local.py, sumpy/expansion/multipole.py, sumpy/symbolic.py
Since Derivatives and Subs are not CSEed due to some issues
derivatives of hankel1 functions and hankel1 functions
end up with different arguments and code generation treats
them seperately. See https://github.com/inducer/sumpy/blob/0fc6535b6ef803e2a8ebd418162274634aead6f9/sumpy/cse.py#L84
Fixes https://github.com/inducer/sumpy/issues/61
=> Add new Hankel1 and BesselJ functions that work with CSE

.github/workflows/ci.yml, sumpy/p2p.py, sumpy/qbx.py, sumpy/tools.py, test/test_matrixgen.py
Moving these to pytential, since sumpy just evaluates a linear set of `(tgtindices, srcindices)` doesn't need to know if they're further broken up into blocks or whatnot.
Required by inducer/pytential#92.
=> Remove BlockIndexRanges and friends from sumpy

.test-conda-env-py3.yml
This reverts commit 596b33c3a5e36189b7340699a430db688f024a8a.
This issue was fixed in the conda package. https://github.com/conda-forge/pocl-feedstock/pull/65
=> Revert "Restrict pocl to <=1.6 for cuda-atomic bug"

sumpy/p2e.py, test/test_matrixgen.py
* Adds some docs to the `__call__` methods to describe the inputs.
* Adds support for object arrays.
(Matrix classes were moved to `pytential` to use `P2QBXL` instead)
=> Add more docs to P2E classes

sumpy/p2e.py
Managed to spot an error in #76.
On the other hand, no one is using the object array support in the P2E classes, so I'm fine with deleting it altogether too. It was initially meant for pytential, since all the `nodes()` are object arrays.
=> Fix rscale dtype inference when using object arrays

sumpy/expansion/multipole.py, sumpy/kernel.py, sumpy/tools.py, test/test_fmm.py
This tests an `AxisTargetDerivative` on a `TargetPointMultiplier` and it's not quite working as expected. 
At least in the case `AxisTargetDerivative(1, TargetPointMultiplier(0, knl))`, I would expect the target derivative to not do much, since the multiplier is on a different component, so it should be equivalent to `TargetPointMultiplier(0, AxisTargetDerivative(1, knl))`. Am I misunderstanding that?
This is more of a question-PR, so
* Does `TargetPointMultiplier` actually support derivatives?
* If yes, is this the right way to apply / check them?
=> Check AxisTargetDerivative on TargetPointMultiplier

.github/workflows/ci.yml, sumpy/fmm.py, test/test_fmm.py
This tracks the refactor of the wrangler and its tree-independent data in https://github.com/inducer/boxtree/pull/29.
Draft because:
=> Track TreeIndependentData refactor from boxtree, remove persistent queue from wrangler

sumpy/expansion/local.py
Just updated and this seems to fail
```
>> sp.sympify("tau", strict=True)
sympy.core.sympify.SympifyError: SympifyError: 'tau'
```
Here it gets called by `diff` somewhere (`subs` still works just fine, but changed it just to be safe).
=> Fix diff with sympy 1.10

sumpy/__init__.py, sumpy/e2e.py, sumpy/expansion/local.py, sumpy/fmm.py, sumpy/p2p.py, test/test_fmm.py
This PR makes a few changes
- Split M2L translation + postprocess_local into two kernels
- Call preprocess and postprocess for non FFT expansions as well. (But only when translation classes data is passed)
- Use a direct loopy kernel for M2L translation
=> Direct loopy kernel

benchmarks/bench_translations.py, examples/curve-pot.py, setup.py, sumpy/codegen.py, sumpy/e2e.py, sumpy/e2p.py, sumpy/expansion/__init__.py, sumpy/expansion/level_to_order.py, sumpy/expansion/local.py, sumpy/expansion/multipole.py, sumpy/kernel.py, sumpy/p2p.py, sumpy/point_calculus.py, sumpy/qbx.py, sumpy/symbolic.py, sumpy/tools.py, sumpy/toys.py, sumpy/visualization.py, test/test_fmm.py, test/test_kernels.py, test/test_misc.py, test/test_tools.py
Noticed in #98 that there were still places that weren't using new-style `super()`, so ran `pyupgrade` over everything (again?). 
The commits are nicer to look at separately.
=> Misc modernize (pyupgrade)

sumpy/e2e.py
This was generating a lot of warnings like
```
loopy/kernel/creation.py:1911: LoopyWarning: in kernel m2l_using_translation_classes_dependent_data: 
The single-writer dependency heuristic added dependencies on instruction ID(s)
'read_src_ibox, translation_offset' to instruction ID 'e2e_insn_3' after
kernel creation is complete. This is deprecated and may stop working in the
future. To fix this, ensure that instruction dependencies are added/resolved 
as soon as possible, ideally at kernel creation time. (add 
'single_writer_after_creation' to silenced_warnings kernel attribute to disable)
```
Not sure if this is the right way to add the required dependencies, so better suggestions welcome!
=> m2l: add dependencies for inlined e2e kernel

sumpy/fmm.py, test/test_fmm.py
Adds a `_disable_translation_classes` hidden option so that we can check the non translation classes kernel.
=> Compute translation_classes_data if not given

.github/workflows/ci.yml, doc/expansion.rst, sumpy/e2e.py, sumpy/expansion/local.py, sumpy/expansion/m2l.py, sumpy/fmm.py, sumpy/toys.py, test/test_fmm.py, test/test_kernels.py, test/test_misc.py
Fixes https://github.com/inducer/sumpy/issues/104
=> Use a separate class for M2L translation and change expansion default to FFT

sumpy/expansion/m2l.py
Without this, sumpy cache retrievals never succeed, because this comparison
https://github.com/inducer/sumpy/blob/daa4118947d5d4a1b892280720d48dde611288e2/sumpy/expansion/local.py#L78=
always returns `False`.
=> M2LTranslationBase: mark immutable, fix equality comparison

.test-conda-env-py3.yml
This forced CI onto Py3.8, as far as I can tell, which may have contributed to a CI failure that I'm not sure I fully understand:
https://gitlab.tiker.net/inducer/sumpy/-/jobs/425789
=> Drop Conda version constraint for symengine

examples/curve-pot.py, examples/expansion-toys.py, examples/sym-exp-complexity.py, requirements.txt, setup.py, sumpy/array_context.py, sumpy/expansion/multipole.py, sumpy/qbx.py, sumpy/symbolic.py, test/test_codegen.py, test/test_cse.py, test/test_fmm.py, test/test_kernels.py, test/test_matrixgen.py, test/test_misc.py, test/test_qbx.py, test/test_tools.py
Ports all the tests to the `arraycontext` infrastructure.
This is not on top of #118 because it can go in without the rest of `sumpy` being ported.
=> Use arraycontext in tests

sumpy/fmm.py
This worked fine before because pypencl didn't care that there was a out-of-bounds access.
=> Fix src_boxes view

.github/workflows/ci.yml, .gitlab-ci.yml, .pylintrc-local.yml, examples/curve-pot.py, sumpy/codegen.py, sumpy/e2e.py, sumpy/e2p.py, sumpy/expansion/__init__.py, sumpy/expansion/level_to_order.py, sumpy/expansion/local.py, sumpy/expansion/m2l.py, sumpy/expansion/multipole.py, sumpy/kernel.py, sumpy/p2e.py, sumpy/p2p.py, sumpy/point_calculus.py, sumpy/qbx.py, sumpy/symbolic.py, sumpy/tools.py, sumpy/toys.py, sumpy/visualization.py
Wanted to run pylint on #139 to root out some issues a bit faster and noticed that it's not on the CI and it has quite a few errors. This should hopefully fix those. 
Most of the issues were in `sumpy.expansions` because some base classes were using methods and attributes from subclasses. Moved some stuff non-trivially to fix that, so it probably needs a more serious look.
=> Add pylint to CI

doc/conf.py
Removes the warning
```
WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('https://docs.python.org/3/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping
```
=> Use Sphinx 1+ syntax for mapping

.github/workflows/ci.yml, requirements.txt, sumpy/codegen.py, sumpy/e2p.py, sumpy/expansion/__init__.py, sumpy/expansion/loopy.py, sumpy/kernel.py, sumpy/p2e.py
- ~~Depends on https://github.com/inducer/loopy/pull/736~~
- Mutually depends on https://github.com/inducer/pytential/pull/194
=> Refactor E2P and P2E

sumpy/e2e.py, sumpy/e2p.py, sumpy/p2e.py, sumpy/p2p.py, sumpy/qbx.py, sumpy/tools.py
This avoids long-lived references to CL kernels held by loopy caches.
=> Make use of `loopy.TranslationUnit.executor`

examples/curve-pot.py, sumpy/toys.py, test/test_fmm.py, test/test_kernels.py, test/test_qbx.py
This takes another chunk from #118. 
Namely, using [make_loopy_program](https://github.com/inducer/arraycontext/blob/main/arraycontext/loopy.py#L42-L64) (or something like it) from `arraycontext` will add a `no_numpy=True` to all kernels. This updates all the tests and other call sites to never pass numpy arrays in.
The stuff in `sumpy.toys` still takes numpy arrays and does all the back and forth behind the scenes.
=> no_numpy in sumpy kernels

sumpy/codegen.py, sumpy/kernel.py
Was playing with adding `__slots__` to pymbolic expressions on the `attrs` branch. That doesn't work with default arguments, since it considers them class attributes and `dataclass` gets confused.
Very few expressions had that issue though, mostly just `CommonSubexpression` and `NaN`, and this fixes it here if we ever want to try it!
=> Pass all arguments to CSE constructor

sumpy/p2p.py
loopy/pyopencl can only tag arrays as vec for arrays of size 2,3,4,8,16. What this does is to divide those into array chunks so that the largest is 128 wide. Also extends the support when strengths and the sources have different dtypes.
=> improve fallback for vec types

test/test_misc.py
It was issuing a warning because it thought it might be a `unittest.TestCase` type thing.
=> Rename TestKernel to not confuse pytest

test/test_distributed.py
This is going to fail on python 3.12 since `distutils` got removed.
=> Remove distutil strtobool

contrib/translations/PDE-reduction and translations.ipynb, contrib/translations/PDE-reduction-symbolic.ipynb
ruff 0.5.6 started linting notebooks by default too (under the `preview` flag at least). This fixes all reported issues in the `contrib/translations` notebooks.
=> Fix ruff issues in notebooks

pyproject.toml
This was mistakenly made optional in #207.
The other dependencies there should be legitimately optional (`fmmlib`, `symengine` and `pyvkfft`).
=> Make sympy a required dependency

.pylintrc-local.yml, contrib/translations/PDE-reduction and translations.ipynb, contrib/translations/PDE-reduction-symbolic.ipynb, pyproject.toml, sumpy/__init__.py, sumpy/assignment_collection.py, sumpy/codegen.py, sumpy/cse.py, sumpy/derivative_taker.py, sumpy/distributed.py, sumpy/expansion/__init__.py, sumpy/expansion/diff_op.py, sumpy/expansion/level_to_order.py, sumpy/expansion/local.py, sumpy/expansion/loopy.py, sumpy/expansion/m2l.py, sumpy/expansion/multipole.py, sumpy/fmm.py, sumpy/kernel.py, sumpy/p2p.py, sumpy/point_calculus.py, sumpy/tools.py, sumpy/toys.py, test/test_fmm.py, test/test_kernels.py, test/test_misc.py
This doesn't include the mypy fixes from #217.
=> Bump to Python 3.10

sumpy/tools.py
Is constructing a list faster than constructing a tuple? Probably doesn't matter..
=> Fix ruff 0.11.4 warning for tuple splatting (RUF005)

.basedpyright/baseline.json, examples/curve-pot.py, sumpy/expansion/local.py, sumpy/expansion/multipole.py, sumpy/kernel.py, sumpy/qbx.py, sumpy/test/geometries.py, sumpy/test/test_target_deriv.py, sumpy/tools.py
=> Fix target derivative taking in line Taylor

.basedpyright/baseline.json, sumpy/kernel.py
Before:
```python
LaplaceKernel(
dim=2,
expression=Call(Variable('log'), (Call(Variable('sqrt'), (Sum((Product((..., ...)), Product((..., ...)))),)),)),
global_scaling_const=Quotient(1, Product((-2, Variable('pi'))))
)
```
After:
```python
LaplaceKernel(dim=2, expression=log(sqrt(d[0]*d[0] + d[1]*d[1])), global_scaling_const=1 / ((-2)*pi))
```
Thoughts? I mostly added it because the repr for the expression is quite unhelpful in the current version.
=> Add custom __repr__ for Kernel
